./c1/1.lox -> ./if/if.lox
./c1/2.lox -> ./if/if.lox
./c1/3.lox -> ./if/if.lox
./c1/4.lox -> ./if/if.lox
./c2/1.lox -> ./if/else.lox
./c2/2.lox -> ./if/else.lox
./c2/3.lox -> ./if/else.lox
./c2/4.lox -> ./if/else.lox
./c3/1.lox -> ./if/else.lox
./c3/2.lox -> ./if/else.lox
./c3/3.lox -> ./if/dangling_else.lox
./c3/4.lox -> ./if/else.lox
./c4/1.lox -> ./if/dangling_else.lox
./c4/2.lox -> ./if/else.lox
./c4/3.lox -> ./if/dangling_else.lox
./c4/4.lox -> ./if/dangling_else.lox
./c5/1.lox -> ./logical_operator/or_truth.lox
./c5/2.lox -> ./logical_operator/or.lox
./c5/3.lox -> ./logical_operator/or.lox
./c5/4.lox -> ./if/if.lox
./c6/1.lox -> ./logical_operator/and_truth.lox
./c6/2.lox -> ./logical_operator/and.lox
./c6/3.lox -> ./logical_operator/and.lox
./c6/4.lox -> ./if/if.lox
./c7/1.lox -> ./while/syntax.lox
./c7/2.lox -> ./while/syntax.lox
./c7/3.lox -> ./while/syntax.lox
./c7/4.lox -> ./while/syntax.lox
./c8/1.lox -> ./for/syntax.lox
./c8/2.lox -> ./for/syntax.lox
./c8/3.lox -> ./for/syntax.lox
./c8/4.lox -> ./for/scope.lox
./c9/1.lox -> ./for/var_in_body.lox
./c9/2.lox -> ./for/statement_condition.lox
./c9/3.lox -> ./for/statement_increment.lox
./c9/4.lox -> ./for/statement_initializer.lox
./cl1/1.lox -> ./class/empty.lox
./cl1/2.lox -> ./class/empty.lox
./cl1/3.lox -> ./variable/undefined_local.lox
./cl1/4.lox -> ./function/body_must_be_block.lox
./cl2/1.lox -> ./constructor/default.lox
./cl2/2.lox -> ./constructor/default.lox
./cl2/3.lox -> ./constructor/default.lox
./cl2/4.lox -> ./constructor/default.lox
./cl3/1.lox -> ./field/on_instance.lox
./cl3/2.lox -> ./field/on_instance.lox
./cl3/3.lox -> ./field/on_instance.lox
./cl3/4.lox -> ./field/on_instance.lox
./cl4/1.lox -> ./method/arity.lox
./cl4/2.lox -> ./class/local_reference_self.lox
./cl4/3.lox -> ./method/arity.lox
./cl4/4.lox -> ./field/method.lox
./cl5/1.lox -> ./this/this_in_method.lox
./cl5/2.lox -> ./this/this_in_method.lox
./cl5/3.lox -> ./field/method_binds_this.lox
./cl5/4.lox -> ./this/closure.lox
./cl6/1.lox -> ./this/this_at_top_level.lox
./cl6/2.lox -> ./this/this_in_top_level_function.lox
./cl6/3.lox -> ./call/object.lox
./cl6/4.lox -> ./field/undefined.lox
./cl7/1.lox -> ./constructor/early_return.lox
./cl7/2.lox -> ./constructor/arguments.lox
./cl7/3.lox -> ./constructor/call_init_explicitly.lox
./cl7/4.lox -> ./constructor/arguments.lox
./cl8/1.lox -> ./constructor/early_return.lox
./cl8/2.lox -> ./constructor/return_value.lox
./cl8/3.lox -> ./constructor/return_value.lox
./cl8/4.lox -> ./constructor/return_value.lox
./f1/3.lox -> ./function/print.lox
./f1/4.lox -> ./function/print.lox
./f2/1.lox -> ./function/parameters.lox
./f2/2.lox -> ./function/empty_body.lox
./f2/3.lox -> ./function/print.lox
./f2/4.lox -> ./function/empty_body.lox
./f3/1.lox -> ./function/parameters.lox
./f3/2.lox -> ./function/parameters.lox
./f3/3.lox -> ./function/parameters.lox
./f3/4.lox -> ./function/parameters.lox
./f4/1.lox -> ./print/missing_argument.lox
./f4/2.lox -> ./scanning/punctuators.lox
./f4/3.lox -> ./function/body_must_be_block.lox
./f4/4.lox -> ./function/missing_comma_in_parameters.lox
./f5/1.lox -> ./function/recursion.lox
./f5/2.lox -> ./return/after_else.lox
./f5/3.lox -> ./return/after_while.lox
./f5/4.lox -> ./return/return_nil_if_no_value.lox
./f6/1.lox -> ./closure/closed_closure_in_function.lox
./f6/2.lox -> ./function/nested_call_with_arguments.lox
./f6/3.lox -> ./closure/closed_closure_in_function.lox
./f6/4.lox -> ./closure/closed_closure_in_function.lox
./f7/1.lox -> ./call/num.lox
./f7/2.lox -> ./function/extra_arguments.lox
./f7/3.lox -> ./function/missing_arguments.lox
./f7/4.lox -> ./call/bool.lox
./f8/1.lox -> ./variable/early_bound.lox
./f8/2.lox -> ./variable/shadow_global.lox
./f8/3.lox -> ./variable/shadow_global.lox
./f8/4.lox -> ./variable/shadow_and_local.lox
./f9/1.lox -> ./closure/assign_to_closure.lox
./f9/2.lox -> ./function/mutual_recursion.lox
./f9/3.lox -> ./closure/assign_to_closure.lox
./f9/4.lox -> ./closure/assign_to_closure.lox
./i1/1.lox -> ./class/inherited_method.lox
./i1/2.lox -> ./class/inherited_method.lox
./i1/3.lox -> ./class/local_inherit_other.lox
./i1/4.lox -> ./class/inherited_method.lox
./i2/1.lox -> ./class/inherited_method.lox
./i2/2.lox -> ./class/inherited_method.lox
./i2/3.lox -> ./inheritance/constructor.lox
./i2/4.lox -> ./class/inherited_method.lox
./i3/1.lox -> ./inheritance/inherit_methods.lox
./i3/2.lox -> ./super/constructor.lox
./i3/3.lox -> ./inheritance/set_fields_from_base_class.lox
./i3/4.lox -> ./inheritance/inherit_methods.lox
./i4/1.lox -> ./class/inherit_self.lox
./i4/2.lox -> ./inheritance/inherit_from_function.lox
./i4/3.lox -> ./inheritance/inherit_from_number.lox
./i4/4.lox -> ./inheritance/inherit_from_function.lox
./i5/1.lox -> ./super/call_same_method.lox
./i5/2.lox -> ./super/super_in_inherited_method.lox
./i5/3.lox -> ./super/super_in_closure_in_inherited_method.lox
./i5/4.lox -> ./super/reassign_superclass.lox
./i6/1.lox -> ./super/no_superclass_call.lox
./i6/2.lox -> ./super/super_at_top_level.lox
./i6/3.lox -> ./super/parenthesized.lox
./i6/4.lox -> ./super/super_without_dot.lox
./r1/1.lox -> ./variable/early_bound.lox
./r1/2.lox -> ./variable/early_bound.lox
./r1/3.lox -> ./variable/early_bound.lox
./r1/4.lox -> ./closure/assign_to_closure.lox
./r2/1.lox -> ./variable/use_global_in_initializer.lox
./r2/2.lox -> ./variable/use_local_in_initializer.lox
./r2/3.lox -> ./variable/use_local_in_initializer.lox
./r2/4.lox -> ./variable/use_local_in_initializer.lox
./r3/1.lox -> ./variable/duplicate_local.lox
./r3/2.lox -> ./variable/collide_with_parameter.lox
./r3/3.lox -> ./variable/duplicate_parameter.lox
./r3/4.lox -> ./variable/duplicate_local.lox
./r4/1.lox -> ./return/at_top_level.lox
./r4/2.lox -> ./return/at_top_level.lox
./r4/3.lox -> ./return/at_top_level.lox
./r4/4.lox -> ./return/at_top_level.lox
./s1/1.lox -> ./bool/equality.lox
./s1/2.lox -> ./operator/add.lox
./s1/3.lox -> ./operator/divide.lox
./s1/4.lox -> ./print/missing_argument.lox
./s10/1.lox -> ./block/scope.lox
./s10/2.lox -> ./variable/shadow_local.lox
./s10/3.lox -> ./variable/shadow_and_local.lox
./s10/4.lox -> ./variable/undefined_local.lox
./s2/1.lox -> ./operator/add.lox
./s2/2.lox -> ./block/empty.lox
./s2/3.lox -> ./scanning/whitespace.lox
./s2/4.lox -> ./string/multiline.lox
./s3/1.lox -> ./operator/comparison.lox
./s3/2.lox -> ./operator/equals.lox
./s3/3.lox -> ./operator/add_num_nil.lox
./s3/4.lox -> ./operator/multiply_nonnum_num.lox
./s4/1.lox -> ./variable/in_middle_of_block.lox
./s4/2.lox -> ./variable/in_middle_of_block.lox
./s4/3.lox -> ./variable/in_middle_of_block.lox
./s4/4.lox -> ./variable/in_middle_of_block.lox
./s5/1.lox -> ./variable/undefined_global.lox
./s5/2.lox -> ./variable/undefined_global.lox
./s5/3.lox -> ./variable/undefined_local.lox
./s5/4.lox -> ./variable/undefined_global.lox
./s6/1.lox -> ./variable/uninitialized.lox
./s6/2.lox -> ./variable/uninitialized.lox
./s6/3.lox -> ./variable/uninitialized.lox
./s6/4.lox -> ./variable/uninitialized.lox
./s7/1.lox -> ./variable/redefine_global.lox
./s7/2.lox -> ./variable/use_global_in_initializer.lox
./s7/3.lox -> ./variable/redefine_global.lox
./s7/4.lox -> ./variable/undefined_global.lox
./s8/1.lox -> ./assignment/global.lox
./s8/2.lox -> ./assignment/global.lox
./s8/3.lox -> ./assignment/associativity.lox
./s8/4.lox -> ./assignment/associativity.lox
./s9/1.lox -> ./block/scope.lox
./s9/2.lox -> ./variable/scope_reuse_in_different_blocks.lox
./s9/3.lox -> ./variable/in_nested_block.lox
./s9/4.lox -> ./block/empty.lox