name: Trigger Fixture Regeneration

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    types:
      - labeled

jobs:
  regenerate_fixtures:
    if: github.event.label.name == 'regenerate-fixtures'
    uses: codecrafters-io/tester-utils/.github/workflows/fixtures.yml@fc856787a017ac1e41121084089b7c358124ed90
    with:
      tester_repo: interpreter-tester
    secrets: inherit