name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup testing environment
        uses: codecrafters-io/interpreter-tester/.github/actions/setup@CC-1779

      - run: make test