name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: setup-env
        name: Setup test environment
        uses: codecrafters-io/codecrafters-action@402e823b111453d1b288e429c52a9d4f9a9bf9ea

      - run: make test
