name: Test

# This workflow sets up the environment required for testing & generating
# fixtures for the interpreter tester against the official jlox implementation.
on: 
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        name: Setup test environment
        uses: codecrafters-io/codecrafters-action@1e17bec1aad5942e5a3fe745a813833658845be1
        with:
          who-to-greet: 'Mona the Octocat'

      - run: make test
